feat(frontend): Apply global font bb-104
BinaryStudioAcademy/bsa-2024-bebalance pull request #113
Opened 2024-08-22 08:50 UTC by JD-Rosales

Summary:

- Added Nunito global font

![image](https://github.com/user-attachments/assets/21736194-0ab2-4a89-8791-67ad21d93076)

2024-08-22 09:19 UTC, fshabanov requested changes

2024-08-22 09:19 UTC, fshabanov commented on apps/frontend/index.html
> +		/>
Let's install font locally. Add to ~/assets/fonts
Then you can create fonts.css file and define a font using @font-face

2024-08-22 13:42 UTC, ViktoriiaKozopas approved these changes
⭐

2024-08-22 15:50 UTC, fshabanov requested changes

2024-08-22 15:50 UTC, fshabanov commented on apps/frontend/src/assets/css/scaffolding.css
> +	font-family: Nunito, Arial, sans-serif;
Not resolved

2024-08-23 07:24 UTC, fshabanov approved these changes

2024-08-23 08:02 UTC, fshabanov approved these changes

2024-08-23 08:02 UTC, merged