fix(frontend): fix user is not saved in redux store after sign in/sign up bb-118
BinaryStudioAcademy/bsa-2024-bebalance pull request #160
Opened 2024-08-23 16:58 UTC by MaxKorop

### Bug fixes

The user is not saved in the store after sign in/sign up. And the token is not saved in the localStorage after sign in.

Sign In (token):
![image](https://github.com/user-attachments/assets/d4222447-e4cc-4a57-af5b-a0167cda38c3)

Sign In (user in the store):
![image](https://github.com/user-attachments/assets/3761523e-80aa-4ebd-9661-d255c216ac4a)

Sign Up (user in the store):
![image](https://github.com/user-attachments/assets/5b543ef1-c55d-4fc8-a957-8f75e2480433)

2024-08-23 17:28 UTC, fshabanov requested changes

2024-08-24 06:57 UTC, fshabanov requested changes

2024-08-24 06:57 UTC, fshabanov commented on package-lock.json
This file shouldn't change

2024-08-24 07:54 UTC, fshabanov requested changes

2024-08-24 07:54 UTC, fshabanov commented on package-lock.json
> +	"version": "1.12.0",
Why did the versions go down?

2024-08-24 11:14 UTC, yulyaolshanska approved these changes

2024-08-24 11:54 UTC, fshabanov requested changes

2024-08-24 11:54 UTC, fshabanov commented on package-lock.json
> +			"version": "1.12.0",
The version should not go down

2024-08-25 06:16 UTC, fshabanov approved these changes

2024-08-25 06:16 UTC, merged