feat(frontend): Sidebar component mobile responsiveness bb-106
BinaryStudioAcademy/bsa-2024-bebalance pull request #192
Opened 2024-08-26 06:08 UTC by JD-Rosales

### Summary
Make the sidebar component responsive.

### Added
- Menu icon

https://github.com/user-attachments/assets/248ecf20-efbe-4532-adfe-c593f0deafd6

2024-08-26 06:31 UTC, fshabanov requested changes

2024-08-26 06:31 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +					<img alt="Menu" className={styles["menu"]} src={menu} />
Use existing Icon component

2024-08-26 06:31 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +				x
Let's use icon here

2024-08-26 06:31 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +				/>
Shouldn't be a checkbox input

2024-08-26 08:43 UTC, fshabanov requested changes

2024-08-26 08:43 UTC, fshabanov commented on apps/frontend/src/libs/components/app/app.tsx
> +						<Header toggleSidebar={toggleSidebar} />
A9

2024-08-26 08:43 UTC, fshabanov commented on apps/frontend/src/libs/components/app/app.tsx
> +	const toggleSidebar = useCallback((): void => {
A10

2024-08-26 08:58 UTC, JD-Rosales commented on apps/frontend/src/libs/components/app/app.tsx
> +						<Header toggleSidebar={toggleSidebar} />
I'm sorry, what does A9 means?

2024-08-26 09:16 UTC, fshabanov commented on apps/frontend/src/libs/components/app/app.tsx
> +						<Header toggleSidebar={toggleSidebar} />
Rule number from [quality criteria](https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/src/javascript.md)

2024-08-26 10:15 UTC, WilhelmWesser approved these changes

2024-08-26 11:12 UTC, fshabanov requested changes
Add a screenshot of mobile view as well

2024-08-26 11:12 UTC, fshabanov commented on apps/frontend/src/libs/components/app/app.tsx
> +		setIsSidebarOpen((previous) => !previous);
`previous` is not a clear name

2024-08-26 12:32 UTC, fshabanov requested changes

2024-08-26 12:32 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +			</button>
Use existing Button component. Add a possibility to add Icon there

2024-08-26 14:47 UTC, fshabanov requested changes

2024-08-26 14:47 UTC, fshabanov commented on apps/frontend/src/libs/components/button/button.tsx
> +	label?: string;
```suggestion
	label: string;
```
Label should be present. Add `hasVisuallyHiddenLabel` prop and if it is true, hide the label using `visually-hidden` class

2024-08-26 14:47 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +					icon={<Icon name="menu" />}
```suggestion
					iconName="menu"
```

2024-08-27 04:35 UTC, fshabanov approved these changes

2024-08-27 04:35 UTC, fshabanov commented
Merge the main branch into yours

2024-08-27 13:36 UTC, merged