fix(backend): added another answer to onboarding answers bb-133
BinaryStudioAcademy/bsa-2024-bebalance pull request #212
Opened 2024-08-27 11:52 UTC by ihorLysak

### Summary

Added missing question to db

2024-08-29 08:00 UTC, fshabanov requested changes

2024-08-30 15:06 UTC, fshabanov approved these changes

2024-08-30 17:02 UTC, ihorLysak commented
Builds locally, fails to build inside of github actions

2024-08-30 17:54 UTC, fshabanov requested changes

2024-08-30 17:54 UTC, fshabanov commented on apps/backend/package.json
> -		"ts-node": "10.9.2",
Add back ts-node to devDependencies to avoid issues with migrations as we had before

2024-08-31 06:20 UTC, fshabanov approved these changes

2024-08-31 06:20 UTC, merged