feat(mobile): add  bottom tab navigator bb-128
BinaryStudioAcademy/bsa-2024-bebalance pull request #214
Opened 2024-08-27 13:28 UTC by Olha-Katran

Add Bottom Bar Navigation and 4 draft screens (Chat, Wheel, Settings, Tasks).

The path to the screens from the bottom navigation is temporarily located in the QuizEntry component.

https://github.com/user-attachments/assets/d4f2b619-d8d4-46c5-aa6f-9779107d6153

![image](https://github.com/user-attachments/assets/ca1d8ef8-34b2-41a7-a452-67d9c8a86a61)

2024-08-27 14:51 UTC, revenets requested changes

2024-08-27 14:51 UTC, revenets commented on apps/mobile/src/libs/components/gradient-tab-icon/gradient-tab-icon.tsx
> +	focused: boolean;
```suggestion
	isFocused: boolean;
```

2024-08-27 14:51 UTC, revenets commented on apps/mobile/src/libs/components/gradient-tab-icon/gradient-tab-icon.tsx
> +const iconGradientOptions = {
Add a return type

2024-08-28 08:51 UTC, anogire approved these changes

2024-08-28 08:59 UTC, revenets approved these changes

2024-08-28 08:59 UTC, merged