feat(backend/shared): save onboarding quiz answers to DB bb-167
BinaryStudioAcademy/bsa-2024-bebalance pull request #227
Opened 2024-08-28 12:10 UTC by yulyaolshanska

- [ ] `quiz_answers_to_users` table migration
```
    onboarding_answers_to_users {
        INTEGER id PK
        INTEGER user_id FK
        INTEGER answer_id FK
        TIMESTAMPTZ created_at
        TIMESTAMPTZ updated_at
    }
```
- [ ] onboarding-answer model with `onboarding_answers` ManyToManyRelation to `users` through `onboarding_answers_to_users`
- [ ] OnboardingAnswerRepository methods:
- `find` answer by id
- `findAll`
- `createUserAnswer`
- [ ] OnboardingAnswerEntity
- [ ] OnboardingAnswerService methods:
- `find` answer by id
- `create`
- [ ] OnboardingController:
- `createUserAnswer`, endpoint: `/onboarding/answer`, method: `POST` to create new answer

2024-08-28 13:46 UTC, fshabanov requested changes

2024-08-28 13:46 UTC, fshabanov commented on apps/backend/src/modules/users/user.model.ts
> +				relation: Model.HasManyRelation,
Isn't it many to many relation?

2024-08-28 13:46 UTC, fshabanov commented on apps/backend/src/modules/onboarding/libs/exceptions/exceptions.ts
> +export { QuizError } from "shared";
```suggestion
export { OnboardingError } from "shared";
```
Let's keep Onboarding and Quiz modules separately

2024-08-28 13:46 UTC, fshabanov commented on packages/shared/src/libs/modules/http/libs/types/http-method.type.ts
> +type HTTPMethod = "DELETE" | "GET" | "POST" | "PUT";
Do you use those?

2024-08-28 13:46 UTC, fshabanov commented on packages/shared/src/modules/onboarding/libs/enums/onboarding-api-path.enum.ts
> +	ROOT: "/",
I think those are not used as well

2024-08-28 13:46 UTC, fshabanov commented on apps/backend/src/modules/onboarding/onboarding.service.ts
> +	}> {
Create a separate type for response

2024-08-28 13:46 UTC, fshabanov commented on apps/backend/src/modules/onboarding/onboarding.service.ts
> +		const answers = await Promise.all(answerIds.map((id) => this.find(id)));
You can create a new method in repository like `findByIds` to find all at once

2024-08-28 15:44 UTC, fshabanov requested changes

2024-08-28 15:44 UTC, fshabanov commented on apps/backend/src/modules/onboarding/onboarding.controller.ts
> +						body: { answerIds: number[] };
Create a shared type for that

2024-08-28 15:44 UTC, fshabanov commented on apps/backend/src/modules/onboarding/onboarding.controller.ts
> +			body: { answerIds: number[] };
Use that type here as well

2024-08-28 15:44 UTC, fshabanov commented on apps/backend/src/modules/onboarding/onboarding.repository.ts
> +	}
Everything should be implemented, no placeholders

2024-08-28 15:44 UTC, fshabanov commented on apps/backend/src/modules/onboarding/onboarding.service.ts
> +		return { addedAnswers: addedAnswers.map((answer) => answer.toObject()) };
```suggestion
		return { answers: addedAnswers.map((answer) => answer.toObject()) };
```

2024-08-29 07:31 UTC, luiqor commented on readme.md
One existing `onboarding_answers_to_users` field can have only one user, and must have at least one user ( .notNullable() ),
One existing `onboarding_answers` field can have many `onboarding_answers_to_users` or don't have them at all (if user doesn't have answers)
```
    onboarding_answers_to_users }o--|| onboarding_answers : answer_id
    onboarding_answers_to_users }o--|| users : user_id
 ```
Same with with users
[useful link](https://pgmodeler.io/support/docs/710-converting-many-to-many-relationships?v=1.1.0)

2024-08-29 15:50 UTC, luiqor approved these changes

2024-08-29 17:53 UTC, fshabanov requested changes

2024-08-29 17:53 UTC, fshabanov commented on apps/backend/src/modules/onboarding/libs/types/types.ts
> +export { type UserDto } from "~/modules/users/users.js";
Shouldn't be exported from here. Import directly from users module where you need it

2024-08-30 05:11 UTC, fshabanov requested changes

2024-08-30 05:11 UTC, fshabanov commented on packages/shared/src/modules/onboarding/libs/enums/onboarding-validation-rule.enum.ts
> +	QUESTIONS_LENGTH: 6,
This will create issues if we decide to add new questions in future. Let's have this check in Backend

2024-08-30 05:11 UTC, fshabanov commented on packages/shared/src/modules/onboarding/libs/types/onboarding-answer-request-body.ts
> +type OnboardingAnswerRequestBody = {
```suggestion
type OnboardingAnswerRequestBodyDto = {
```

2024-08-30 11:33 UTC, ihorLysak commented on packages/shared/src/modules/onboarding/libs/types/onboarding-answer-request-body-dto.type.ts
> +type OnboardingAnswerRequestBodyDto = {
What does the _**body**_ in the name of the type mean?

2024-08-30 15:44 UTC, fshabanov commented on apps/backend/src/modules/onboarding/onboarding.repository.ts
> +		return await this.onboardingQuestionModel.query().resultSize();
Can we use `.count` here?

2024-08-30 17:23 UTC, fshabanov commented on apps/backend/src/modules/onboarding/onboarding.repository.ts
> +		return await this.onboardingQuestionModel.query().resultSize();
Not that it is not suitable, as far as I know `count` doesn't fetch everything from the DB, that's why I prefer it

2024-08-30 17:24 UTC, fshabanov approved these changes

2024-08-30 17:24 UTC, merged