feat(frontend): analyzing screen mobile responsiveness bb-136
BinaryStudioAcademy/bsa-2024-bebalance pull request #231
Opened 2024-08-28 14:56 UTC by iqbalalayubbi

QA Note

- [ ]  Up to 521px the title is not centered.
- [ ] When the screen is reduced, the circles on the background intersect and the background does not look like on the mockup

2024-08-29 06:10 UTC, WilhelmWesser approved these changes

2024-08-29 10:21 UTC, fshabanov requested changes

2024-08-29 10:21 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/analyzing/styles.module.css
> +/* 480px, 768px, 1024px and 1200px */
```suggestion
```

2024-08-29 17:45 UTC, yulyaolshanska approved these changes

2024-08-30 10:28 UTC, revenets approved these changes

2024-08-30 15:19 UTC, fshabanov approved these changes

2024-08-30 15:25 UTC, merged