fix(frontend): "You are unauthorized to access the requested resource." error message is shown on the Sign-In/ Sign-Up page bb-222
BinaryStudioAcademy/bsa-2024-bebalance pull request #248
Opened 2024-08-30 10:47 UTC by marharita08

## Summary
Fixed issue: "You are unauthorized to access the requested resource." error message is shown on the Sign-In/ Sign-Up page.

## Updated
- app.tsx: check for token and user existence before call getAuthenticatedUser action

2024-08-30 11:15 UTC, ihorLysak approved these changes
seems fine to me

2024-08-30 17:49 UTC, fshabanov requested changes

2024-08-30 17:49 UTC, fshabanov commented on apps/frontend/src/libs/components/app/app.tsx
> +		const loadAuthenticatedUser = async (): Promise<void> => {
Should be handled in slice - if there's no token, we don't make a call

2024-08-31 06:24 UTC, fshabanov requested changes

2024-08-31 06:24 UTC, fshabanov commented on apps/frontend/src/modules/auth/slices/actions.ts
> +	const { user } = getState().auth;
No need to check for a user

2024-08-31 06:24 UTC, fshabanov commented on apps/frontend/src/modules/auth/slices/actions.ts
> +	return token && !user ? await authApi.getAuthenticatedUser() : null;
Avoid complex ternary operators.
```
const hasToken = Boolean(token)

if (!hasToken) {
  return null;
}

return get()
```

2024-08-31 07:02 UTC, fshabanov approved these changes

2024-08-31 07:02 UTC, merged