feat(frontend/backend): quiz functionality bb-89
BinaryStudioAcademy/bsa-2024-bebalance pull request #263
Opened 2024-08-31 15:39 UTC by Mikoyzskie

-  Get all questions with answers from Backend
-  Group questions by categories
-  Display questions group by group

2024-08-31 17:20 UTC, ihorLysak commented on packages/shared/tsconfig.json
> +		"../../apps/backend/src/modules/quiz/libs/types/quiz-questions-get-all-response.type.ts"
This shouldn't be here

2024-08-31 17:21 UTC, ihorLysak commented on packages/shared/src/modules/quiz/libs/types/quiz-answers-dto.type.ts
> +type QuizAnswersDto = {
Looks like a Dto for a single entity, maybe QuizAnswerDto would be better?

2024-08-31 17:21 UTC, ihorLysak commented on packages/shared/src/modules/quiz/libs/types/quiz-questions-dto.type.ts
> +type QuizQuestionsDto = {
same as with QuizAnswersDto

2024-08-31 17:24 UTC, ihorLysak commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/styles.module.css
> +.btn-secondary button {
maybe move this to Button container?

2024-08-31 17:27 UTC, ihorLysak commented on apps/frontend/src/pages/quiz/libs/components/progress-bar/progress-bar.tsx
> +import React from "react";
We can use React without importing it

2024-08-31 18:40 UTC, fshabanov requested changes

2024-08-31 18:40 UTC, fshabanov commented on apps/backend/src/modules/quiz/libs/types/quiz-answers-dto.type.ts
> +type QuizAnswersDto = {
I believe this should be in shared

2024-08-31 18:40 UTC, fshabanov commented on apps/backend/src/modules/quiz/libs/types/quiz-answers-dto.type.ts
> +type QuizAnswersDto = {
```suggestion
type QuizAnswerDto = {
```

2024-08-31 18:40 UTC, fshabanov commented on apps/backend/src/modules/quiz/libs/types/quiz-questions-dto.type.ts
> +type QuizQuestionsDto = {
Should be in shared

2024-08-31 18:40 UTC, fshabanov commented on apps/backend/src/modules/quiz/quiz-questions.entity.ts
> +class QuizQuestionsEntity {
```suggestion
class QuizQuestionsEntity implements Entity {
```

2024-08-31 18:40 UTC, fshabanov commented on apps/backend/src/modules/quiz/quiz.repository.ts
> +import { QuizQuestionsEntity } from "~/modules/quiz/quiz-questions.entity.js";
```suggestion
import { QuizQuestionsEntity } from "./quiz-questions.entity.js";
```

2024-08-31 18:40 UTC, fshabanov commented on apps/backend/src/modules/quiz/quiz.repository.ts
> +class QuizQuestionsRepository {
```suggestion
class QuizQuestionsRepository implements Repository {
```

2024-08-31 18:40 UTC, fshabanov commented on apps/backend/src/modules/quiz/quiz.service.ts
> +class QuizQuestionsService {
```suggestion
class QuizQuestionsService implements Service {
```

2024-08-31 18:40 UTC, fshabanov commented on apps/frontend/src/libs/components/quiz-question/quiz-question.tsx
> +	options?: { label: string; value: string }[];
Create a separate type for that

2024-08-31 18:40 UTC, fshabanov commented on apps/frontend/src/modules/quiz/slices/quiz.slice.ts
> +};
```suggestion
type State = {
	dataStatus: ValueOf<typeof DataStatus>;
	questions: QuizQuestionsDto[];
};

const initialState: State = {
	dataStatus: DataStatus.IDLE,
	questions: [],
};
```

2024-08-31 18:40 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/quiz-form.tsx
> +import { DataStatus } from "~/libs/enums/data-status.enum.js";
```suggestion
import { DataStatus } from "~/libs/enums/enums.js";
```

2024-08-31 18:40 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/quiz-form.tsx
> +import { ProgressBar } from "~/pages/quiz/libs/components/components.js";
Move to ~/libs/components/components

2024-08-31 18:40 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/quiz-form.tsx
> +	}, [questions]);
Too much logic for frontend, should be done in backend

2024-08-31 18:40 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/styles.module.css
> +.btn button,
B10

2024-08-31 18:40 UTC, fshabanov commented on packages/shared/src/modules/quiz/libs/enums/quiz-api-path.enum.ts
> +	QUIZ_QUESTION: "/questions",
```suggestion
	ANSWERS: "/answers",
	QUESTIONS: "/questions",
```

2024-09-02 11:13 UTC, ihorLysak commented on apps/frontend/src/modules/quiz/quiz-api.ts
> +	public async getQuestions(): Promise<QuizQuestionsGetAllReponseDto> {
maybe getAllQuestions? Feels more descriptive to me

2024-09-02 11:15 UTC, ihorLysak commented on apps/backend/src/modules/quiz/quiz.service.ts
> +	update(): Promise<unknown> {
Why not?

2024-09-02 14:31 UTC, fshabanov requested changes

2024-09-02 14:31 UTC, fshabanov commented on apps/backend/src/libs/modules/server-application/libs/constants/constants.ts
> +	`${APIPath.QUIZ}${QuizApiPath.QUESTION}`,
It shouldn't be a white route

2024-09-02 14:31 UTC, fshabanov commented on apps/backend/src/modules/quiz/quiz-questions.entity.ts
> +import { type Entity } from "~/libs/types/entity.type.js";
```suggestion
import { type Entity } from "~/libs/types/types.js";
```

2024-09-02 14:31 UTC, fshabanov commented on apps/backend/src/modules/quiz/quiz.repository.ts
> +import { type Repository } from "~/libs/types/repository.type.js";
```suggestion
import { type Repository } from "~/libs/types/types.js";
```

2024-09-02 14:31 UTC, fshabanov commented on apps/backend/src/modules/quiz/quiz.repository.ts
> +		return questions.map((question) =>
B27

2024-09-02 14:31 UTC, fshabanov commented on apps/backend/src/modules/quiz/quiz.service.ts
> +		const user = await this.quizQuestionsRepository.create(
Why does creating a quiz question return a user?

2024-09-02 14:31 UTC, fshabanov commented on apps/backend/src/modules/quiz/quiz.service.ts
> +	update(): Promise<unknown> {
Should be implemented

2024-09-02 14:31 UTC, fshabanov commented on apps/frontend/src/libs/components/input/input.tsx
> +type options = {
Should be in a separate file, capitalized

2024-09-02 14:31 UTC, fshabanov commented on apps/frontend/src/libs/components/progress-bar/progress-bar.tsx
> +import CheckIcon from "~/assets/img/check-icon.svg?react";
We have a separate Icon component

2024-09-02 14:31 UTC, fshabanov commented on apps/frontend/src/libs/components/progress-bar/progress-bar.tsx
> +	const elementsArray = Array.from({ length: steps });
B17

2024-09-02 14:31 UTC, fshabanov commented on apps/frontend/src/libs/components/quiz-question/quiz-question.tsx
> +type options = {
Should be in a separate file. Same type for input as well

2024-09-02 14:31 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/quiz-form.tsx
> +import { DataStatus } from "~/libs/enums/data-status.enum.js";
```suggestion
import { DataStatus } from "~/libs/enums/enums.js";
```

2024-09-02 14:31 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/quiz-form.tsx
> +	}, [dataStatus, questions]);
Too much logic for Frontend, should be in Backend

2024-09-02 14:31 UTC, fshabanov commented on packages/shared/src/modules/quiz/libs/enums/quiz-api-path.enum.ts
> +	QUESTION: "/question",
```suggestion
	QUESTIONS: "/questions",
```

2024-09-03 12:18 UTC, fshabanov requested changes

2024-09-03 12:18 UTC, fshabanov commented on apps/frontend/src/libs/components/input/input.tsx
> +	type OPTIONS,
```suggestion
	type Options,
```

2024-09-03 12:18 UTC, fshabanov commented on apps/frontend/src/libs/components/quiz-question/quiz-question.tsx
> +	type OPTIONS,
```suggestion
	type Options,
```

2024-09-03 12:18 UTC, fshabanov commented on apps/frontend/src/modules/quiz/slices/quiz.slice.ts
> +	questions: { items: QuizQuestionDto[][] };
```suggestion
	questionsByCategories: QuizQuestionDto[][]
```

2024-09-03 12:18 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/quiz-form.tsx
> +	const handleBackStep = useCallback(() => {
```suggestion
	const handlePreviousStep = useCallback(() => {
```

2024-09-03 12:18 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/quiz-form.tsx
> +				<ProgressBar currentStep={currentStep} steps={questions.length} />
```suggestion
				<ProgressBar currentStep={currentStep} numberOfSteps={questions.length} />
```

2024-09-03 12:18 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/quiz-form.tsx
> +								}))}
Move this to a separate variable

2024-09-03 12:18 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/styles.module.css
> +.btn button,
Not resolved

2024-09-03 13:21 UTC, fshabanov requested changes

2024-09-03 13:21 UTC, fshabanov commented on apps/frontend/src/libs/types/input-options.type.ts
> +type Options = {
```suggestion
type RadioInputOption = {
```
Change the file name as well

2024-09-03 13:21 UTC, fshabanov commented on apps/frontend/src/pages/quiz/libs/components/quiz-form/quiz-form.tsx
>  		defaultValues: { value: "" },
It doesn't look like a valid default value, we shouldn't have mock values

2024-09-04 14:52 UTC, fshabanov approved these changes

2024-09-05 04:43 UTC, fshabanov approved these changes

2024-09-05 04:43 UTC, merged