feat(frontend) sign-out functionality bb-241
BinaryStudioAcademy/bsa-2024-bebalance pull request #264
Opened 2024-08-31 16:13 UTC by ihorLysak

### Summary

Implemented sign-out

https://github.com/user-attachments/assets/377c99b3-793e-4c76-922b-25ef91f775a9

2024-08-31 18:31 UTC, fshabanov requested changes

2024-08-31 18:31 UTC, fshabanov commented on apps/frontend/src/libs/components/button/button.tsx
> +				variant === "sidebarItem" && styles["last"],
I don't think this should be a part of button. Should be handled in sidebar

2024-08-31 18:31 UTC, fshabanov commented on apps/frontend/src/modules/auth/slices/auth.slice.ts
> +		logOut: (state) => {
Let's create a separate action for that

2024-09-01 14:43 UTC, fshabanov requested changes

2024-09-01 14:43 UTC, fshabanov commented on apps/frontend/src/libs/components/button/styles.module.css
> +.last {
I believe you can remove it now

2024-09-01 14:43 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +				<button className={styles["signOut-btn"]} onClick={handleSignOut}>
Use our Button component

2024-09-01 14:43 UTC, fshabanov commented on apps/frontend/src/modules/auth/slices/auth.slice.ts
> +		logOut: (state) => {
Remove this one

2024-09-01 17:55 UTC, fshabanov requested changes

2024-09-01 17:55 UTC, fshabanov commented on apps/frontend/src/libs/components/button/styles.module.css
> +.sidebarItem-button {
Do you use this style?

2024-09-01 18:01 UTC, ihorLysak commented on apps/frontend/src/libs/components/button/styles.module.css
> +.sidebarItem-button {
that is strange, I remember removing it

2024-09-02 07:05 UTC, fshabanov approved these changes

2024-09-02 07:05 UTC, merged