fix(frontend): moved AuthWrapper from protected route into Root component bb-258
BinaryStudioAcademy/bsa-2024-bebalance pull request #274
Opened 2024-09-02 13:27 UTC by ihorLysak

### Summary
Fixed by moving authWrapper from ProtectedRoute component into individual page (currently Root component)
<img width="1440" alt="Screenshot 2024-09-02 at 16 26 48" src="https://github.com/user-attachments/assets/cc10e262-4986-494b-a371-4dc3a98abccb">
<img width="1440" alt="Screenshot 2024-09-02 at 16 26 38" src="https://github.com/user-attachments/assets/bcd0c63c-858c-4997-839e-bf0fad52a0ab">

2024-09-02 15:20 UTC, fshabanov requested changes

2024-09-02 15:20 UTC, fshabanov commented on apps/frontend/src/pages/root/root.tsx
> +const Root: React.FC = () => {
I don't like this solution. It means in future for any new screens we need to wrap in in AuthWrapper. We should keep AuthWrapper in ProtectedRoute and think of another way of dealing with the issue

2024-09-02 16:25 UTC, marharita08 approved these changes

2024-09-03 08:04 UTC, fshabanov requested changes

2024-09-03 08:04 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/libs/constants/routes-with-auth-wrapper.constant.ts
> +const routesWithoutAuthWrapper = [AppRoute.QUIZ] as string[];
```suggestion
const routesWithoutAuthWrapper = [AppRoute.QUIZ] as ValueOf<typeof AppRoute>[];
```

2024-09-03 09:23 UTC, fshabanov requested changes

2024-09-03 09:23 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/libs/helpers/has-auth-wrapper.helper.ts
> +import { type AppRoute } from "~/libs/enums/app-route.enum.js";
```suggestion
import { type AppRoute } from "~/libs/enums/enums.js";
```

2024-09-03 09:23 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +import { hasAuthWrapper } from "./libs/helpers/has-auth-wrapper.helper.js";
```suggestion
import { hasAuthWrapper } from "./libs/helpers/helpers.js";
```

2024-09-03 09:23 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +	if (user && hasAuthWrapper(pathname as ValueOf<typeof AppRoute>)) {
Let's simplify:
```
if (!user) {
  return <Navigate ... />
}

if (hasAuthWrapper(...)) {
  return <AuthWrapper>{component}</AuthWrapper>
}

return component
```

2024-09-03 09:23 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/libs/constants/routes-with-auth-wrapper.constant.ts
> +const routesWithoutAuthWrapper = [AppRoute.QUIZ] as ValueOf<typeof AppRoute>[];
```suggestion
const ROUTES_WITHOUT_AUTH_WRAPPER: ValueOf<typeof AppRoute>[] = [AppRoute.QUIZ];
```

2024-09-03 09:23 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/libs/constants/routes-with-auth-wrapper.constant.ts
> +import { AppRoute } from "~/libs/enums/enums.js";
Change the file name

2024-09-03 10:43 UTC, ihorLysak commented
Sorry for non-informative commit name, i pushed it before the daily meeting

2024-09-03 11:41 UTC, yulyaolshanska approved these changes

2024-09-03 12:32 UTC, fshabanov requested changes

2024-09-03 12:32 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/libs/constants/routes-without-auth-wrapper.constant.ts
> +>[];
```suggestion
const ROUTES_WITHOUT_AUTH_WRAPPER: ValueOf<typeof AppRoute>[] = [AppRoute.QUIZ];
```

2024-09-03 16:26 UTC, ihorLysak commented
I accidentaly made work intended for another branch, those changes are reverted now

2024-09-03 18:49 UTC, fshabanov approved these changes

2024-09-03 18:55 UTC, merged