fix(frontend): remade backgrounds for quiz and not-found pages bb-327
BinaryStudioAcademy/bsa-2024-bebalance pull request #336
Opened 2024-09-07 14:51 UTC by ihorLysak

###Summary

fixed background images for safari on not-found and quiz pages
<img width="1440" alt="Screenshot 2024-09-07 at 17 46 58" src="https://github.com/user-attachments/assets/995cb8cc-1133-495b-bf39-d7d188269e59">
<img width="1440" alt="Screenshot 2024-09-07 at 17 47 27" src="https://github.com/user-attachments/assets/d0ea605b-02f5-4559-bee1-c30c9cc86ef0">

2024-09-07 16:28 UTC, fshabanov requested changes

2024-09-07 16:28 UTC, fshabanov commented on apps/frontend/src/assets/img/elipses-not-found.svg
Can we use existing ones?

2024-09-08 10:03 UTC, WilhelmWesser approved these changes

2024-09-09 13:23 UTC, revenets approved these changes

2024-09-10 10:06 UTC, fshabanov approved these changes

2024-09-10 10:13 UTC, merged