feat(frontend): settings screen bb-334
BinaryStudioAcademy/bsa-2024-bebalance pull request #376
Opened 2024-09-10 13:27 UTC by ihorLysak

### Summary
created settings screen
<img width="1440" alt="Screenshot 2024-09-10 at 16 27 39" src="https://github.com/user-attachments/assets/987bfb06-fc19-4960-a65b-2b3f6dab7030">

2024-09-10 14:44 UTC, ihorLysak commented on apps/frontend/src/index.tsx
> +								element: <Auth />,
moved them down because they are not protected

2024-09-10 15:45 UTC, fshabanov requested changes
Let's have week days in 2 rows and frequency answers shorter, they are too long

2024-09-10 15:45 UTC, fshabanov commented on apps/frontend/src/assets/img/sign-out.svg
Why was it removed?

2024-09-10 15:45 UTC, fshabanov commented on apps/frontend/src/modules/users/slices/actions.ts
> +	`${sliceName}/saveNotificationAnswers`,
```suggestion
	`${sliceName}/save-notification-answers`,
```

2024-09-10 15:45 UTC, fshabanov commented on apps/frontend/src/pages/libs/constants/constants.ts
> +} from "./notification-questions-options.constant.js";
Create each at a separate file

2024-09-10 15:45 UTC, fshabanov commented on apps/frontend/src/pages/libs/constants/constants.ts
> +export {
We shouldn't have ~/pages/libs. If it is something global, move to ~/libs

2024-09-10 16:09 UTC, ihorLysak commented on apps/frontend/src/assets/img/sign-out.svg
We don't use it anywhere

2024-09-11 08:11 UTC, ihorLysak commented
<img width="1440" alt="Screenshot 2024-09-11 at 11 11 05" src="https://github.com/user-attachments/assets/8fe93ada-eff6-4484-a88e-43057b072beb">

2024-09-11 10:51 UTC, fshabanov requested changes
Center everything in the layout

2024-09-11 10:51 UTC, fshabanov commented on apps/frontend/src/libs/types/types.ts
> +export { type NotificationQuestionsFormValues } from "./notification-questions-form-values.types.js";
```suggestion
export { type NotificationQuestionsFormValues } from "./notification-questions-form-values.type.js";
```

2024-09-11 10:51 UTC, fshabanov commented on apps/frontend/src/pages/settings/libs/constants/settings-notification-frequency-options.constant.ts
> +const SETTINGS_NOTIFICATION_FREQUENCY_OPTIONS = [
We already have `NOTIFICATION_FREQUENCY_OPTIONS`, which has the same values

2024-09-11 11:21 UTC, ihorLysak commented
<img width="1440" alt="Screenshot 2024-09-11 at 14 20 04" src="https://github.com/user-attachments/assets/dd68cb77-7e41-486e-9c34-3a7e825a26a6">
Centered layout, extendded notification options width for symmetry

2024-09-11 13:36 UTC, fshabanov requested changes

2024-09-11 13:36 UTC, fshabanov commented on apps/frontend/src/modules/auth/slices/actions.ts
> +	await storage.drop(StorageKey.TOKEN);
I don't think it should be here. Also, not part of your task

2024-09-11 14:09 UTC, merged