12 feat add protected routing frontend
BinaryStudioAcademy/bsa-2024-bebalance pull request #39
Opened 2024-08-18 11:14 UTC by marharita08

## Created
- protected route component

## Updated
- components.tsx to export protected route component
- index.tsx to wrap root path in protected route

## Issue
closes #12

2024-08-18 11:37 UTC, fshabanov requested changes

2024-08-18 11:37 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +	return <Navigate replace to={AppRoute.SIGN_IN} />;
You shouldn't check the status. You should check whether the user is present or not

2024-08-18 11:37 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +const ProtectedRoute: React.FC = () => {
This component should receive `component` and `redirectTo` as props. You will either display that component or redirect to `redirectTo` screen

2024-08-18 20:08 UTC, WilhelmWesser approved these changes

2024-08-18 20:08 UTC, WilhelmWesser approved these changes

2024-08-19 06:40 UTC, revenets approved these changes

2024-08-19 08:53 UTC, fshabanov requested changes

2024-08-19 08:53 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +import { Navigate } from "react-router-dom";
Should be imported from ~/libs/components/components.js

2024-08-19 08:53 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +import { ValueOf } from "shared";
Should be imported from ~/libs/types/types.js

2024-08-19 08:53 UTC, fshabanov commented on apps/frontend/src/modules/auth/slices/auth.slice.ts
> +import { UserSignUpResponseDto } from "~/modules/users/libs/types/types.js";
```suggestion
import { UserSignUpResponseDto } from "~/modules/users/users.js";
```

2024-08-19 09:08 UTC, fshabanov approved these changes

2024-08-19 09:09 UTC, fshabanov commented
Merge the `main` branch into yours

2024-08-19 09:31 UTC, fshabanov commented
Merge it again, please :)

2024-08-19 09:47 UTC, fshabanov approved these changes

2024-08-19 09:47 UTC, merged