feat(mobile): dynamic text welcome screen bb-305
BinaryStudioAcademy/bsa-2024-bebalance pull request #391
Opened 2024-09-11 14:26 UTC by Olha-Katran

Add dynamic text for welcome screen which appears line by line 

Video:

https://github.com/user-attachments/assets/a727edf9-3b5d-49fc-9a49-9c9040292faf

2024-09-11 14:55 UTC, revenets requested changes

2024-09-11 14:55 UTC, revenets commented on apps/mobile/src/libs/helpers/create-animated-text/create-animated-text.tsx
> +		Animated.timing(animatedOpacity, {
Use `reanimated` library for animation

2024-09-14 15:20 UTC, fshabanov requested changes

2024-09-14 15:20 UTC, fshabanov commented on apps/mobile/src/libs/helpers/create-animated-text/create-animated-text.tsx
> +const createAnimatedText = (
Let's move to a custom hook, as we did on web

2024-09-14 15:20 UTC, fshabanov commented on apps/mobile/src/screens/welcome/libs/constants/constants.ts
> +export { AnalyzingText } from "./analyzing-text.constants";
```suggestion
export { AnalyzingText } from "./analyzing-text.constant";
```

2024-09-14 15:20 UTC, fshabanov commented on apps/mobile/src/screens/welcome/welcome.tsx
> +import React, { useCallback, useEffect, useState } from "react";
Should import hooks from ~/libs/hooks/hooks

2024-09-18 08:17 UTC, closed without merging