feat(mobile): editing wheel results bb-344
BinaryStudioAcademy/bsa-2024-bebalance pull request #394
Opened 2024-09-11 14:59 UTC by Olha-Katran

Create scores editing form using slider with gradient color
Add nested route from "wheel" to "Edit my wheel results"
Add style to page "Wheel"
Add placeholder place for checkbox form
Add getScore slice

For now - use mock data, without save editing changes

screenshot:
<img src="https://github.com/user-attachments/assets/8872276f-aa84-4932-ae89-0eab6963c158" width="250"> <img src="https://github.com/user-attachments/assets/b7e638a9-9b28-418b-bd7d-5ac1fc970430" width="250"> <img src="https://github.com/user-attachments/assets/f332307b-f55e-420d-ac4a-765e50a5949f" width="250">

Video: 

https://github.com/user-attachments/assets/fd984e51-173d-4391-a65e-979a72f35ccf

2024-09-11 15:49 UTC, revenets requested changes

2024-09-11 15:49 UTC, revenets commented on apps/mobile/src/libs/components/white-background-wrapper/white-background-wrapper.tsx
> +const WhiteBackgroundWrapper: React.FC<Properties> = ({ children }) => {
Don't think that we actually need this, Can we just pass the `style` prop to ScreenWrapper?

2024-09-11 15:49 UTC, revenets commented on apps/mobile/src/screens/wheel/wheel.tsx
> +						5 Aug 2024, Tuesday
I think we can use actual date here, not mocked value

2024-09-11 15:49 UTC, revenets commented on apps/mobile/src/screens/edit-wheel-results/components/scores-edit-form/scores-edit-form.tsx
> +	);
We should use react-hook-form for this form as well

2024-09-11 16:50 UTC, fshabanov requested changes

2024-09-11 16:50 UTC, fshabanov commented on apps/mobile/src/screens/edit-wheel-results/components/scores-edit-form/scores-edit-form.tsx
> +		//Todo implement edit scores
The Backend is already merged, implement this as well

2024-09-12 22:11 UTC, Shcracoziabra approved these changes

2024-09-12 22:11 UTC, Shcracoziabra commented on apps/mobile/src/libs/components/screen-wrapper/screen-wrapper.tsx
Its a good idea to add style to the wrapper!
And what about  adding a Direction enum for directions mentioned in this component?
```ts
const Direction = {
	BOTTOM: "bottom",
	LEFT: "left",
	RIGHT: "right",
	TOP: "top",
} as const;
```

2024-09-12 22:12 UTC, Shcracoziabra commented on apps/mobile/src/libs/components/screen-wrapper/screen-wrapper.tsx
Its a good idea to add style to the wrapper!
And what about  adding a Direction enum for directions mentioned in this component?
```ts
const Direction = {
	BOTTOM: "bottom",
	LEFT: "left",
	RIGHT: "right",
	TOP: "top",
} as const;
```

2024-09-12 22:14 UTC, Shcracoziabra approved these changes

2024-09-12 22:49 UTC, Shcracoziabra commented on apps/mobile/src/libs/helpers/helpers.ts
>  export { createRadioButtonProperties } from "./create-radio-button-properties/create-radio-button.properties";
```suggestion
export { createRadioButtonProperties } from "./create-radio-button-properties/create-radio-button-properties.helper";
```

2024-09-12 22:49 UTC, Shcracoziabra commented on apps/mobile/src/libs/components/slider-content/slider-content.tsx
>  const MIN_SLIDER_VALUE = 0;
How about creating enum?
```ts
const SliderValue = {
  MAX: 10,
  MIN: 0,
 } as const;
 ```

2024-09-12 22:49 UTC, Shcracoziabra commented on apps/mobile/src/screens/wheel/styles.ts
> +		display: "flex",
`display: flex ` is default for React Native layout, this prop is redundant.

2024-09-16 16:02 UTC, closed without merging