15 feat add loader
BinaryStudioAcademy/bsa-2024-bebalance pull request #45
Opened 2024-08-18 16:41 UTC by yulyaolshanska

### Summary
This PR implements the loader component for the application.

### Created
- Loader component
- file for color variables

### Changes
- **index.tsx:** Added Suspense with loader

<img width="1019" alt="image" src="https://github.com/user-attachments/assets/de26bc93-bfd2-4dc4-991b-71ac2f65c978">

<img width="1016" alt="image" src="https://github.com/user-attachments/assets/5ce860dd-dfd9-49e2-84e7-a21e38686670">

2024-08-18 17:08 UTC, fshabanov requested changes
This is not a loader, this is a circular progress bar. You needed to create a Loader, which will be used when we have some loading data. Example: https://loading.io/assets/mod/spinner/rolling/lg.gif

2024-08-18 17:13 UTC, yulyaolshanska commented
> This is not a loader, this is a circular progress bar. You needed to create a Loader, which will be used when we have some loading data. Example: https://loading.io/assets/mod/spinner/rolling/lg.gif

but the percentage should remains as in the figma?

2024-08-18 17:16 UTC, fshabanov commented
> > This is not a loader, this is a circular progress bar. You needed to create a Loader, which will be used when we have some loading data. Example: https://loading.io/assets/mod/spinner/rolling/lg.gif
> 
> but the percentage should remains as in the figma?

No, no percentage. The one in figma is not a loader, it is a circular progress bar, which will be used in a completely different part

2024-08-18 17:21 UTC, yulyaolshanska commented
> > > This is not a loader, this is a circular progress bar. You needed to create a Loader, which will be used when we have some loading data. Example: https://loading.io/assets/mod/spinner/rolling/lg.gif
> > 
> > 
> > but the percentage should remains as in the figma?
> 
> No, no percentage. The one in figma is not a loader, it is a circular progress bar, which will be used in a completely different part

I thought this was a loader design 🤦‍♀️. Does that mean I can make a loader with any design?

2024-08-18 17:37 UTC, fshabanov commented
> > > > This is not a loader, this is a circular progress bar. You needed to create a Loader, which will be used when we have some loading data. Example: https://loading.io/assets/mod/spinner/rolling/lg.gif
> > > 
> > > 
> > > but the percentage should remains as in the figma?
> > 
> > 
> > No, no percentage. The one in figma is not a loader, it is a circular progress bar, which will be used in a completely different part
> 
> I thought this was a loader design 🤦‍♀️. Does that mean I can make a loader with any design?

Yep, you can take something close to the app design

2024-08-18 21:08 UTC, WilhelmWesser approved these changes

2024-08-19 06:42 UTC, revenets approved these changes

2024-08-19 06:43 UTC, revenets commented
Just wondering, can we use the same gradient color for the loader as we use for the buttons' hover state?

2024-08-19 08:00 UTC, fshabanov requested changes

2024-08-19 08:00 UTC, fshabanov commented on apps/frontend/src/libs/components/loader/loader.tsx
> +			<div className={styles["loader"]}></div>
```suggestion
			<div className={styles["loader"]} />
```

2024-08-19 08:17 UTC, yulyaolshanska commented
> Just wondering, can we use the same gradient color for the loader as we use for the buttons' hover state?

<img width="271" alt="image" src="https://github.com/user-attachments/assets/5c453136-3506-4dfa-b2ff-9371e09338ca">

Like this?

2024-08-19 09:11 UTC, fshabanov requested changes

2024-08-19 09:11 UTC, fshabanov commented on apps/frontend/src/libs/components/loader/loader.tsx
> +import React from "react";
We don't need this import in a web project

2024-08-19 11:23 UTC, merged