feat(frontend): add default answer and quick tip bb-460
BinaryStudioAcademy/bsa-2024-bebalance pull request #475
Opened 2024-09-17 16:11 UTC by MaxKorop

### Summary

- Added quick tip after question
- Changed default answer

### Screenshots
![image](https://github.com/user-attachments/assets/9609e1b0-85bb-4326-a8b4-aea4bd2cf7d3)

2024-09-17 17:47 UTC, ihorLysak approved these changes

2024-09-17 19:28 UTC, fshabanov requested changes

2024-09-17 19:28 UTC, fshabanov commented on apps/frontend/src/libs/components/checkbox/checkbox.tsx
> +					!hasTip && "visually-hidden",
If there's no tip, then don't display it at all. Currently you are hiding an empty thing and it doesn't make sense

2024-09-18 06:20 UTC, fshabanov approved these changes

2024-09-18 06:23 UTC, merged