feat: get authenticated user bb-14
BinaryStudioAcademy/bsa-2024-bebalance pull request #53
Opened 2024-08-19 12:31 UTC by Mikoyzskie

- After refreshing the page, current user is received and saved in app state
- Use the token saved in localStorage to get current user and save that user to app state

2024-08-19 14:04 UTC, fshabanov requested changes

2024-08-19 14:04 UTC, fshabanov commented on apps/frontend/src/modules/users/slices/users.slice.ts
> +	user: undefined | UserGetAllItemResponseDto;
```suggestion
	user: null | UserGetAllItemResponseDto;
```

2024-08-19 14:04 UTC, fshabanov commented on apps/frontend/src/modules/users/slices/users.slice.ts
> +	user: undefined,
```suggestion
	user: null,
```

2024-08-19 14:04 UTC, fshabanov commented on apps/frontend/src/modules/users/slices/users.slice.ts
> +			state.user = { email: action.payload.email, id: action.payload.id };
```suggestion
			state.user = action.payload;
```

2024-08-19 21:44 UTC, WilhelmWesser approved these changes

2024-08-20 06:15 UTC, revenets approved these changes

2024-08-20 07:38 UTC, fshabanov requested changes

2024-08-20 07:38 UTC, fshabanov commented on apps/frontend/src/modules/users/slices/actions.ts
> +const getUser = createAsyncThunk<
```suggestion
const getAuthenticatedUser = createAsyncThunk<
```
Change everywhere

2024-08-20 07:38 UTC, fshabanov commented on apps/frontend/src/modules/users/slices/actions.ts
> +const getUser = createAsyncThunk<
You should call this action in ~/libs/components/app/app.tsx

2024-08-20 11:22 UTC, fshabanov requested changes

2024-08-20 11:22 UTC, fshabanov commented on apps/frontend/src/modules/users/slices/actions.ts
> +>(`${sliceName}/get_user`, (_, { extra }) => {
```suggestion
>(`${sliceName}/get-authenticated-user`, (_, { extra }) => {
```

2024-08-20 11:28 UTC, fshabanov approved these changes

2024-08-20 11:34 UTC, merged