feat(frontend): Profile Page Responsiveness bb-513
BinaryStudioAcademy/bsa-2024-bebalance pull request #531
Opened 2024-09-22 15:25 UTC by KeidsID

Related to issue #513, this PR will add mobile responsiveness for the `/profile` page.

https://github.com/user-attachments/assets/00c03fb3-003d-4399-bb6c-4c41e0933aca

2024-09-22 15:54 UTC, fshabanov requested changes

2024-09-22 15:54 UTC, fshabanov commented on apps/frontend/src/pages/profile/profile.tsx
> +					<ProfileSection title="Danger Zone">
Not sure about using "Danger Zone" for a sign out. Discuss with QA

2024-09-23 07:27 UTC, WilhelmWesser requested changes

2024-09-23 07:27 UTC, WilhelmWesser commented on package-lock.json
Please, pay attention to lock file. If there are no new dependencies it should not be changed

2024-09-23 11:34 UTC, marharita08 commented on apps/frontend/src/pages/profile/profile.tsx
> +					<ProfileSection title="Profile">
'Profile' is title of the whole page, not of the section. I think it should have bigger font-size than other titles on this page.

2024-09-24 00:51 UTC, Mikoyzskie commented
Also I made changes on some buttons on this page.

2024-09-24 06:15 UTC, merged