feat(backend/frontend/shared): Add notes to tasks bb-419
BinaryStudioAcademy/bsa-2024-bebalance pull request #535
Opened 2024-09-23 08:46 UTC by JD-Rosales

### Summary

- Added check-note-access-to-task hook on backend.
- Added UI for viewing and adding notes.
- Added redux action for getting task notes and adding task notes.

https://github.com/user-attachments/assets/6c9f20e6-5c19-4cdf-8919-40d9b709c626

2024-09-23 09:22 UTC, luiqor reviewed
The branch has conflicts that need to be resolved, likely stemming from the "task modal actions".
After resolving these conflicts, please take a look at that: the Task-card component is also used in the modal. You'll need to disable notes button and change the icon color in the modal.

2024-09-23 11:24 UTC, marharita08 commented on apps/backend/src/db/migrations/20240918040515_add_task_notes_table.ts
> +	TASK_NOTES: "task_notes",
Did you add this table to db schema in readme file?

2024-09-23 11:24 UTC, marharita08 commented on apps/backend/src/modules/tasks/libs/hooks/check-note-access-to-task.hook.ts
> +const checkNoteAccessToTask =
What difference between this and checkAccessToTask?

2024-09-23 11:28 UTC, fshabanov requested changes

2024-09-23 11:28 UTC, fshabanov commented on apps/backend/src/db/migrations/20240918040515_add_task_notes_table.ts
> +import { type Knex } from "knex";
We already have a migration to add this table in main, it was added in a backend part of your task

2024-09-23 11:28 UTC, fshabanov commented on apps/backend/src/modules/tasks/libs/hooks/check-note-access-to-task.hook.ts
> +		if ((user as UserDto).id !== task?.userId) {
`checkAccessToTask` does exactly the same, remove this one

2024-09-23 11:28 UTC, fshabanov commented on apps/backend/src/modules/tasks/task.controller.ts
> +	 * /tasks/notes/:id:
```suggestion
	 * /tasks/:id/notes:
```

2024-09-23 11:28 UTC, fshabanov commented on apps/backend/src/modules/tasks/task.repository.ts
> +			.orderBy("createdAt", "asc");
```suggestion
			.orderBy("createdAt", SortOrder.ASC);
```

2024-09-23 11:28 UTC, fshabanov commented on apps/frontend/src/libs/helpers/handle-click-outside/handle-click-outside.helper.ts
> +		const handleClickOutside = (event: MouseEvent | TouchEvent): void => {
`handleClickOutside` is already defined outside, let's not have the same name

2024-09-23 11:28 UTC, fshabanov commented on apps/frontend/src/modules/tasks/slices/tasks.slice.ts
> +	task_notes: TaskNoteDto[];
```suggestion
	taskNotes: TaskNoteDto[];
```

2024-09-23 11:28 UTC, fshabanov commented on apps/frontend/src/pages/tasks/libs/components/notes/notes.tsx
> +		},
Should be in a separate constant file

2024-09-23 11:28 UTC, fshabanov commented on apps/frontend/src/pages/tasks/libs/components/task-card/task-card.tsx
> +			)}
Notes shouldn't close when adding a new note

2024-09-23 11:28 UTC, fshabanov commented on packages/shared/src/modules/tasks/libs/enums/tasks-api-path.enum.ts
> +	NOTES_$ID: "/notes/:id",
```suggestion
	NOTES_$ID: "/:id/notes",
```

2024-09-24 06:22 UTC, fshabanov requested changes

2024-09-24 06:22 UTC, fshabanov commented on apps/frontend/src/libs/components/icon/libs/maps/icon-name-to-svg.map.ts
> +	arrow_next: ArrowNext,
```suggestion
	arrowNext: ArrowNext,
```
Keep the same naming styles

2024-09-24 06:22 UTC, fshabanov commented on apps/frontend/src/libs/helpers/handle-click-outside/handle-click-outside.helper.ts
> +		const detectClickOutside = (event: MouseEvent | TouchEvent): void => {
```suggestion
		const handleDetectClickOutside = (event: MouseEvent | TouchEvent): void => {
```

2024-09-24 06:22 UTC, fshabanov commented on apps/frontend/src/libs/helpers/handle-click-outside/handle-click-outside.helper.ts
> +	callback: () => void,
```suggestion
	onClickOutside: () => void,
```

2024-09-24 06:22 UTC, fshabanov commented on apps/frontend/src/pages/tasks/libs/components/notes/notes.tsx
> +			})(event);
```suggestion
			void handleSubmit(onSubmit)(event);
```

2024-09-24 06:22 UTC, fshabanov commented on apps/frontend/src/pages/tasks/libs/components/notes/notes.tsx
> +	const reference = handleClickOutside<HTMLDivElement>(onNoteClose);
Reference for what? Give a better name

2024-09-24 06:22 UTC, fshabanov commented on apps/frontend/src/pages/tasks/libs/components/task-card/task-card.tsx
> +
Duplicate

2024-09-24 07:52 UTC, fshabanov requested changes

2024-09-24 07:52 UTC, fshabanov commented on apps/frontend/src/libs/helpers/handle-click-outside/handle-click-outside.helper.ts
> +	const reference = useRef<null | T>(null);
Let's send a reference as an argument

2024-09-24 07:52 UTC, fshabanov commented on apps/frontend/src/libs/helpers/handle-click-outside/handle-click-outside.helper.ts
> +const handleClickOutside = <T extends HTMLElement>(
```suggestion
const useClickOutside = <T extends HTMLElement>(
```
Let's make it a hook

2024-09-24 07:52 UTC, fshabanov commented on apps/frontend/src/pages/tasks/libs/components/task-card/task-card.tsx
> +									iconColor=""
```suggestion
```

2024-09-24 08:43 UTC, JD-Rosales commented
Submit button is currently not visible because of a bug in icon button variant. @KeidsID is working a fix on that.

2024-09-24 09:26 UTC, fshabanov approved these changes

2024-09-24 09:26 UTC, merged