feat(backend/shared) add ai chat multi task endpoints bb-340
BinaryStudioAcademy/bsa-2024-bebalance pull request #563
Opened 2024-09-24 18:44 UTC by AndriiLevin

change change/explain one task for tasks array
change the text of the notification for AI Assistant error

2024-09-24 20:30 UTC, fshabanov requested changes

2024-09-24 20:30 UTC, fshabanov commented on apps/backend/src/modules/ai-assistant/libs/helpers/change-tasks/generate-change-task-suggestions-response.helper.ts
> +import { ChatMessageAuthor, ChatMessageType, HTTPCode } from "shared";
Don't import directly from shared

2024-09-24 20:30 UTC, fshabanov commented on apps/backend/src/modules/ai-assistant/libs/helpers/helpers.ts
> +} from "~/modules/ai-assistant/libs/helpers/change-tasks/run-change-task-by-category-options.helper.js";
```suggestion
} from "./change-tasks/run-change-task-by-category-options.helper.js";
```

2024-09-24 20:30 UTC, fshabanov commented on apps/backend/src/modules/ai-assistant/libs/helpers/helpers.ts
> +} from "~/modules/ai-assistant/libs/helpers/explain-tasks/run-explain-tasks-option.helper.js";
```suggestion
} from "./explain-tasks/run-explain-tasks-option.helper.js";
```

2024-09-24 20:30 UTC, fshabanov commented on apps/backend/src/modules/ai-assistant/libs/helpers/suggest-task-by-category/generate-suggest-task-response.helper.ts
> +import { OpenAIErrorMessage } from "~/libs/modules/open-ai/libs/enums/open-ai-error-template.enum.js";
```suggestion
import { OpenAIErrorMessage } from "~/libs/modules/open-ai/open-ai.js";
```

2024-09-24 21:17 UTC, AndriiLevin commented on apps/backend/src/modules/ai-assistant/libs/helpers/helpers.ts
> +} from "~/modules/ai-assistant/libs/helpers/change-tasks/run-change-task-by-category-options.helper.js";
auto rename....
fixed

2024-09-25 06:06 UTC, fshabanov approved these changes

2024-09-25 06:06 UTC, fshabanov commented on apps/backend/src/modules/ai-assistant/ai-assistant.controller.ts
> +	 *               payload:  # Исправлен отступ здесь
```suggestion
	 *               payload: 
```

2024-09-25 07:35 UTC, WilhelmWesser approved these changes

2024-09-25 08:09 UTC, KotenkoNata commented
Now to send request explain-tasks and change-tasks- I need to send 

```
{
                    “categoryId”: 8,
                    “categoryName”: “Mental”,
                    “description”: “Spend 10 minutes each day practicing mindfulness meditation to help reduce stress and improve your mental clarity. You can use an app or simply focus on your breathing in a quiet space.“,
                    “dueDate”: “2024-09-29T20:11:15.546Z”,
                    “label”: “Daily Mindfulness Session”
                },
``` 

Maybe better without dueDate as we have for suggest-tasks.

2024-09-25 09:24 UTC, AndriiLevin commented
I deleted dueDate so there is a need to re-create Assistant.

2024-09-25 10:45 UTC, fshabanov approved these changes

2024-09-25 10:45 UTC, merged