feat(mobile): ai chat service bb-441
BinaryStudioAcademy/bsa-2024-bebalance pull request #570
Opened 2024-09-25 09:01 UTC by KotenkoNata

-  Display categories with 3 lowest values.
- Create a service to handle backend chat.
 - Add a "Send Request" button (needs to be refined).
 - Send requests with selected categories and display the tasks that have been received.

Preview 

[3+lowest.webm](https://github.com/user-attachments/assets/dbda987d-bd28-4666-a2b8-220c66c2ba0d)

[checkbox.webm](https://github.com/user-attachments/assets/c54675d8-2268-4c0e-9099-d62bbcc0be6c)

2024-09-25 09:12 UTC, fshabanov commented on apps/mobile/src/screens/chat/chat.tsx
> +		<ScreenWrapper edges={[]} style={[globalStyles.flex1, styles.container]}>
```suggestion
		<ScreenWrapper style={[globalStyles.flex1, styles.container]}>
```
Can we remove it, if we don't pass anything?

2024-09-25 09:12 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-box/libs/components/components.ts
> +export { AiTask } from "./ai-task/ai-task";
```suggestion
export { AITask } from "./ai-task/ai-task";
```

2024-09-25 09:14 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/checkbox-buttons/checkbox-buttons.tsx
> +		<ChatMessage isUser={false} text={CHECKBOX_SELECTOR_TEXT}>
```suggestion
		<ChatMessage text={CHECKBOX_SELECTOR_TEXT}>
```
Let's make false by default

2024-09-25 09:14 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/generate-task-buttons/generate-task-buttons.tsx
> +				text: "No smth else",
```suggestion
				text: "No, something else",
```

2024-09-25 09:15 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/generate-task-buttons/generate-task-buttons.tsx
> +				<Button appearance="outlined" label="No smth else" onPress={handleNo} />
```suggestion
				<Button appearance="outlined" label="No, something else" onPress={handleNo} />
```

2024-09-25 09:15 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/generate-task-buttons/generate-task-buttons.tsx
> +	const handleYes = useCallback(() => {
Not a clear naming

2024-09-25 09:16 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/loader/libs/enums/delay.enum.ts
> +const DotDelays = {
```suggestion
const DotDelay = {
```
Change file name to `dot-delay.enum.ts`

2024-09-25 09:17 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/loader/libs/helpers/get-animated-styles.helper.ts
> +const getAnimatedStyle = (scaleValue: SharedValue<number>): Property =>
Let's convert it to a custom hook. Hooks cannot be called inside of helpers
![image](https://github.com/user-attachments/assets/60e49baa-181d-46b2-95cb-ba09d366eaab)

2024-09-25 09:17 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/loader/loader.tsx
> +const INITIAL_SCALE_VALUE = 1;
Create enum

2024-09-25 09:17 UTC, fshabanov commented on apps/mobile/src/slices/chat/actions.ts
> +>(`${sliceName}/init-conversation`, async (_, { extra }) => {
```suggestion
>(`${sliceName}/initialize-conversation`, async (_, { extra }) => {
```

2024-09-25 09:29 UTC, revenets requested changes

2024-09-25 09:29 UTC, revenets commented on apps/mobile/src/libs/components/chat-header/styles.ts
> +		display: "flex",
```suggestion
```

2024-09-25 09:29 UTC, revenets commented on apps/mobile/src/libs/components/chat-message/styles.ts
> +		flex: 1,
Use globalStyles instead
```suggestion
```

2024-09-25 09:29 UTC, revenets commented on apps/mobile/src/screens/chat/chat.tsx
> +							</>
```suggestion
							<>
								{isLoading ? <Loader /> : (
								   threadId && <ChatButtons />
								)}
							</>
```

2024-09-25 09:29 UTC, revenets commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/generate-task-buttons/generate-task-buttons.tsx
> +	const handleNo = useCallback(() => {
```suggestion
	const handleNoPress = useCallback(() => {
```

2024-09-25 09:29 UTC, revenets commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/generate-task-buttons/generate-task-buttons.tsx
> +	const handleYes = useCallback(() => {
```suggestion
	const handleYesPress = useCallback(() => {
```

2024-09-25 12:32 UTC, KotenkoNata commented on apps/mobile/src/navigations/bottom-tabs-navigator/bottom-tabs-navigator.tsx
> +					},
No, doesn't work.

2024-09-25 12:33 UTC, KotenkoNata commented on apps/mobile/src/navigations/bottom-tabs-navigator/bottom-tabs-navigator.tsx
> +					headerShown: true,
Yes, but for other screens, it is false. That's why it is true.

2024-09-25 12:40 UTC, KotenkoNata commented
Add regenerate tasks. 

[regenerate.webm](https://github.com/user-attachments/assets/1210fbbf-b746-4117-8698-c94ba44dada6)

2024-09-25 13:21 UTC, fshabanov commented on apps/mobile/src/navigations/bottom-tabs-navigator/bottom-tabs-navigator.tsx
> +					headerShown: true,
Not sure to understand. If it is `true` by default, then we don't need to add this

2024-09-25 13:24 UTC, fshabanov requested changes

2024-09-25 13:24 UTC, fshabanov commented on apps/mobile/src/libs/components/chat-message/chat-message.tsx
> +	isUser,
```suggestion
	isUser = false,
```

2024-09-25 13:24 UTC, fshabanov commented on apps/mobile/src/packages/categories/categories.ts
> +export { categoriesSelectedValidationSchema } from "./libs/validation-schemas";
```suggestion
export { categoriesSelectedValidationSchema } from "./libs/validation-schemas/validation-schemas";
```

2024-09-25 13:33 UTC, KotenkoNata commented on apps/mobile/src/navigations/bottom-tabs-navigator/bottom-tabs-navigator.tsx
> +					headerShown: true,
When I create Root navigation, I turn headerShown to false for all NavigationItem. That's why for AI chat I need  `headerShown: true`

2024-09-25 13:33 UTC, revenets commented
> Add regenerate tasks.
> 
>  regenerate.webm

I think it would be great to add some extra padding at the bottom, because when the chat is full screen, the last message appears to close to the native navigation tab

2024-09-25 13:56 UTC, KotenkoNata commented
Extra padding at the bottom

it was before 
<img width="403" alt="Screenshot 2024-09-25 at 15 53 48" src="https://github.com/user-attachments/assets/671d117b-fc84-4d08-9793-8e134705df01">

add more space
<img width="403" alt="Screenshot 2024-09-25 at 15 53 24" src="https://github.com/user-attachments/assets/36002c1b-085a-423e-9d3d-0f2470d0ab80">

2024-09-25 14:07 UTC, KotenkoNata commented
Do we need to have the exact text and buttons with web version? I have a look to [PR](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/pull/576#issue-2548091067) and we have differences.

2024-09-25 17:11 UTC, revenets commented
Please fix unresolved comments

2024-09-25 17:36 UTC, fshabanov requested changes

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/libs/components/chat-message/chat-message.tsx
> +		<Icon color={BaseColor.LIGHT_GRAY} name="account-circle" size={ICON_SIZE} />
Let's use user avatar here

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/navigations/bottom-tabs-navigator/bottom-tabs-navigator.tsx
> +					tabBarStyle: { display: "none" },
Not resolved

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/packages/chat/chat-api.ts
> +	public async initiateConversation(): Promise<ThreadMessageCreateDto> {
Not resolved

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/packages/chat/libs/helpers/check-is-task-type.helper.ts
> +};
Not resolved

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/screens/chat/chat.tsx
> +		<ScreenWrapper edges={[]} style={[globalStyles.flex1, styles.container]}>
Not resolved

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-box/chat-box.tsx
> +	const isUser = author === "user";
Not resolved

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-box/libs/components/components.ts
> +export { AiTask } from "./ai-task/ai-task";
Not resolved

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/checkbox-buttons/checkbox-buttons.tsx
> +		<ChatMessage isUser={false} text={CHECKBOX_SELECTOR_TEXT}>
Not resolved

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/generate-task-buttons/generate-task-buttons.tsx
> +				text: "No smth else",
Not resolved

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/generate-task-buttons/generate-task-buttons.tsx
> +					label="No smth else"
```suggestion
					label="No, something else"
```

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/initial-chat-message/initial-chat-message.tsx
> +				isUser={false}
```suggestion
```

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/initial-chat-message/initial-chat-message.tsx
> +			<ChatMessage isUser={false} text="Here are your Wheel results:">
```suggestion
			<ChatMessage text="Here are your Wheel results:">
```

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/loader/libs/hooks/use-animated-scale-styles.hook.ts
> +type Property = {
```suggestion
type ReturnValue = {
```

2024-09-25 17:36 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/loader/loader.tsx
> +		<ChatMessage isUser={false} style={globalStyles.mt8}>
```suggestion
		<ChatMessage style={globalStyles.mt8}>
```

2024-09-25 19:22 UTC, KotenkoNata commented on apps/mobile/src/navigations/bottom-tabs-navigator/bottom-tabs-navigator.tsx
> +					tabBarStyle: { display: "none" },
Sorry, maybe I haven't updated the page, and that's why I didn't fix some comments

2024-09-25 20:55 UTC, anogire approved these changes

2024-09-26 05:37 UTC, revenets approved these changes

2024-09-26 06:06 UTC, fshabanov requested changes

2024-09-26 06:06 UTC, fshabanov commented on apps/mobile/src/libs/components/components.tsx
> +export { FlatList } from "react-native";
We already have export from `react-native`, combine

2024-09-26 06:06 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/accept-tasks/accept-tasks.tsx
> +		<ChatMessage isUser={false} text={FEEDBACK_TEXT}>
```suggestion
		<ChatMessage text={FEEDBACK_TEXT}>
```
Check in other places as well

2024-09-26 06:06 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/generate-task-buttons/generate-task-buttons.tsx
> +		<ChatMessage isUser={false} text={CONFIRMATION_TEXT}>
```suggestion
		<ChatMessage text={CONFIRMATION_TEXT}>
```

2024-09-26 06:06 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/chat-buttons/libs/components/generate-task-buttons/generate-task-buttons.tsx
> +					label="No smth else"
Not fixed

2024-09-26 06:06 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/loader/libs/hooks/use-animated-scale-styles.hook.ts
> +	}));
B27

2024-09-26 08:40 UTC, fshabanov approved these changes

2024-09-26 08:40 UTC, fshabanov commented on apps/mobile/src/screens/chat/libs/components/loader/libs/hooks/use-animated-scale-styles.hook.ts
> +	});
```suggestion
const useAnimatedScaleStyle = (scaleValue: SharedValue<number>): ReturnValue => {
	return useAnimatedStyle(() => {
		return {
			transform: [{ scale: scaleValue.value }],
		};
	}});
```

2024-09-26 09:14 UTC, merged