feat(mobile): task management bb-445
BinaryStudioAcademy/bsa-2024-bebalance pull request #577
Opened 2024-09-25 16:34 UTC by Olha-Katran

Add text palceholder for empty active/past tasks
Add background for task screen.

Screenshot: 
<img src="https://github.com/user-attachments/assets/626178ea-0635-4698-af47-4c8bb1e3f054" width="250">
<img src="https://github.com/user-attachments/assets/e2f689e5-f79f-46cc-899e-86ced46ca050" width="250">
<img src="https://github.com/user-attachments/assets/fab02387-11de-4096-a427-179802309eef" width="250">

Video: 

https://github.com/user-attachments/assets/52d9b2a5-e3ca-4569-91b4-14c26b52c375

2024-09-25 17:19 UTC, revenets requested changes

2024-09-25 17:19 UTC, revenets commented on apps/mobile/src/libs/components/page-switcher/page-switcher.tsx
> +			if (!isDisabled) {
Why not just pass the `isDisabled ` as TouchableOpacity prop?

2024-09-25 17:19 UTC, revenets commented on apps/mobile/src/screens/tasks/tasks.tsx
> +							<ScrollView
I'd suggest using FlatList instead.

2024-09-25 17:19 UTC, revenets commented on apps/mobile/src/screens/tasks/tasks.tsx
> +
Why do we need this? Regarding the logic below - we already have filtered tasks returned from the store.

2024-09-25 17:19 UTC, revenets commented on apps/mobile/src/screens/tasks/tasks.tsx
> +							</View>
This can be moved to a separate component and used as a ListEmptyComponent prop of FlatList

2024-09-25 17:40 UTC, fshabanov commented on apps/mobile/src/assets/images/background.png
Prefer svg

2024-09-27 15:59 UTC, revenets approved these changes

2024-09-27 15:59 UTC, revenets commented on apps/mobile/src/screens/tasks/tasks.tsx
> +		(item: TaskDto, index: number) => index.toString(),
Use` item.id` instead

2024-09-27 18:39 UTC, revenets commented on apps/mobile/src/slices/task/task.slice.ts
> +	currentTasks: [],
It seems to be unused. Do we still need it?

2024-09-27 19:00 UTC, merged