feat: change task after deadline bb-446
BinaryStudioAcademy/bsa-2024-bebalance pull request #579
Opened 2024-09-25 17:17 UTC by Shcracoziabra

#446 

### Overview

- [x] Created a modal that will appear on the Tasks screen when the countdown for the exact task ends.
- [x] Changed the status of a task after its deadline after user action (extend deadline, mark as completed or skip).
- [x] Modal appears in the Tasks tab if there is at least one task expired.
- [x] User can horisontally slide expired tasks if there are several ones.
- [x] Notification is triggered on the task dueDate property to warn user of the task expired.

### Summary:

- added @notifee/react-native to display expired task notification;
- created ExpiredTasksModal component for expired tasks;
- adjusted DeadlineCountdown component to change appearance when expired or active;
- adjusted TaskCard component to change appearance when expired or active;
- added updateTaskAfterDeadline method to tasks api;
- created updateTaskAfterDeadline thunk for tasks slice;
- added activeTasks and expiredTasks to the tasks slice to make task screen update on state change possible;
- added setActiveTasks, setExpiredTasks, addExpiredTask to slice actions.

### Screenshots

<img src="https://github.com/user-attachments/assets/53f6d9a5-ee3e-4fbf-ad50-e25bca302617" alt="expire tasks modal" width="300" />
<img src="https://github.com/user-attachments/assets/79c53926-7a5f-4473-93b8-3c0df34da405" alt="push notifications" width="300" />

### Userflow
<video src="https://github.com/user-attachments/assets/4689b6dc-e665-47d4-a0a8-739c71761b34" />

2024-09-25 17:34 UTC, revenets requested changes

2024-09-25 17:34 UTC, revenets commented on apps/mobile/src/libs/components/deadline-countdown/libs/hooks/use-countdown.hook.ts
> +	onExpire = (): void => {},
```suggestion
	onExpire,
```

2024-09-25 17:34 UTC, revenets commented on apps/mobile/src/libs/components/deadline-countdown/libs/hooks/use-countdown.hook.ts
> +				onExpire();
```suggestion
				onExpire?.();
```

2024-09-25 17:34 UTC, revenets commented on apps/mobile/src/libs/components/deadline-countdown/deadline-countdown.tsx
> +	onExpire = (): void => {},
```suggestion
	onExpire,
```

2024-09-25 17:34 UTC, revenets commented on apps/mobile/src/libs/components/task-card/task-card.tsx
> +	onSkip = (): void => {},
```suggestion
	onComplete,
	onExpire,
	onSkip,
```

2024-09-25 17:44 UTC, fshabanov requested changes

2024-09-25 17:44 UTC, fshabanov commented on apps/mobile/src/libs/components/expired-tasks-modal/expired-tasks-modal.tsx
> +	const scrollViewWidth = useMemo(() => tasks.length * width, [tasks, width]);
```suggestion
	const scrollViewWidth = useMemo(() => {
	  return tasks.length * width
	}, [tasks, width]);
```
Let's make it more readable

2024-09-25 17:44 UTC, fshabanov commented on apps/mobile/src/libs/helpers/add-notification-on-tasks-expired/add-notifications-on-tasks-expired.helper.ts
> +	}
Create a separate package for that

2024-09-27 05:34 UTC, revenets approved these changes

2024-09-27 10:07 UTC, merged