feat: loader component bb-19
BinaryStudioAcademy/bsa-2024-bebalance pull request #58
Opened 2024-08-19 17:20 UTC by ToyLess78

PR Title:
feat: Create LoaderWrapper component

PR Description:

This PR introduces a new LoaderWrapper component that will be used as a common loading indicator across the application. The LoaderWrapper component is designed to provide a consistent and reusable way to display a loading state while data is being fetched.

Changes include:

Created LoaderWrapper component that utilizes 
Integrated the LoaderWrapper component within the Auth screen to display the loader when dataStatus is "pending".

Issue Reference:
Resolves #19 - Create a common LoaderWrapper component to be used while data is fetching.

Additional Notes:

This component can be easily extended or customized in the future if additional functionality is required.
Please review the changes and provide feedback if necessary.

2024-08-19 18:26 UTC, anogire commented
Please, delete issue from your PR. It shouldn't automatically close.

2024-08-19 19:32 UTC, revenets requested changes

2024-08-19 19:32 UTC, revenets commented on apps/mobile/src/libs/components/common/loader-wrapper/loader-wrapper.tsx
> +};
You may not want to affect the layout of the child component. And I believe we can get rid of the additional wrapper for ActivityIndicator.
```suggestion
	return isLoading ? (
		  <ActivityIndicator 
		      color={BaseColor.BG_BLUE}
		      size="large"
		      style={[
		          globalStyles.flex1,
		          globalStyles.justifyContentCenter,
		          globalStyles.alignItemsCenter
		      ]} />
	) : (
		<>{children}</>
	);
};
```

2024-08-19 19:40 UTC, ToyLess78 commented
<img width="303" alt="Знімок екрана 2024-08-19 о 22 37 45" src="https://github.com/user-attachments/assets/61ce2bf8-6b7f-4452-92ba-3e04b81c5226">

2024-08-19 20:42 UTC, anogire commented on apps/mobile/src/libs/components/common/loader-wrapper/loader-wrapper.tsx
> +import { globalStyles } from "~/libs/styles/styles";
import { BaseColor } from "~/libs/enums/enums"

2024-08-19 20:45 UTC, anogire commented on apps/mobile/src/screens/auth/auth.tsx
>  			<ScreenWrapper>
Let's use DataStatus from "~/libs/enums/enums"

2024-08-20 07:44 UTC, fshabanov requested changes

2024-08-20 07:44 UTC, fshabanov commented on apps/mobile/src/libs/components/common/loader-wrapper/loader-wrapper.tsx
> +import { ActivityIndicator } from "react-native";
export from ~/libs/components/components

2024-08-20 07:44 UTC, fshabanov commented on apps/mobile/src/libs/components/components.tsx
> +export { LoaderWrapper } from "./common/loader-wrapper/loader-wrapper";
The components in this file are already common, no need to create `common` folder

2024-08-20 09:54 UTC, revenets approved these changes

2024-08-20 10:49 UTC, fshabanov requested changes

2024-08-20 10:49 UTC, fshabanov commented on CHANGELOG.md
> +- add continuous delivery bb-3 ([#62](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/62)) ([4106756](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/commit/4106756bc7ecd91
Undo these changes, add .prettierignore as it was written in the internal chat

2024-08-20 10:49 UTC, fshabanov commented on apps/mobile/src/libs/components/loader-wrapper/loader-wrapper.tsx
> +import { BaseColor } from "~/libs/enums/app/base-color.enum";
```suggestion
import { BaseColor } from "~/libs/enums/enums";
```

2024-08-20 13:41 UTC, fshabanov approved these changes

2024-08-20 13:41 UTC, merged