feat:(frontend): task explanations bb-340
BinaryStudioAcademy/bsa-2024-bebalance pull request #589
Opened 2024-09-26 10:32 UTC by Mikoyzskie

- Add explain task button
- Generate explanation from openai
-

2024-09-26 11:13 UTC, Mikoyzskie commented
![image](https://github.com/user-attachments/assets/262c18fe-b925-406b-bb53-48765cbddb96)

2024-09-26 13:16 UTC, fshabanov requested changes
After displaying the explanations, we should have only 2 buttons: Add these tasks and I don't like these tasks. We shouldn't have explain button again

2024-09-26 13:16 UTC, fshabanov commented on apps/frontend/src/modules/chat/slices/chat.slice.ts
> +				for (const message of newMessages) {
We now have this logic in a helper, in shared

2024-09-26 13:20 UTC, ihorLysak reviewed
Shouldn't be too hard to resolve conflicts for this one.

2024-09-27 10:44 UTC, fshabanov approved these changes

2024-09-27 10:44 UTC, fshabanov commented on apps/frontend/src/pages/chat/libs/components/buttons-controller/libs/components/suggestions-manipulation-options/suggestions-manipulation-options.tsx
> +	isExplained,
```suggestion
	isExplained = false,
```

2024-09-27 14:16 UTC, fshabanov approved these changes

2024-09-27 14:16 UTC, merged