feat: Quiz introduction screen bb-87
BinaryStudioAcademy/bsa-2024-bebalance pull request #97
Opened 2024-08-21 09:29 UTC by JD-Rosales

Summary

Added quiz introduction screen
Added fluid props for the button component

2024-08-21 10:49 UTC, fshabanov requested changes

2024-08-21 10:49 UTC, fshabanov commented on apps/frontend/src/index.tsx
> +								path: AppRoute.QUIZ,
This is not a part of Auth screen

2024-08-21 10:49 UTC, fshabanov commented on apps/frontend/src/pages/auth/components/quiz-introduction-screen/quiz-introduction-screen.tsx
> +import lifeBalanceWheel from "~/assets/img//life-balance-wheel.svg";
```suggestion
import lifeBalanceWheel from "~/assets/img/life-balance-wheel.svg";
```

2024-08-22 06:42 UTC, revenets approved these changes

2024-08-22 07:03 UTC, fshabanov requested changes

2024-08-22 07:03 UTC, fshabanov commented on apps/frontend/src/pages/quiz/quiz.tsx
> +};
We don't need `getScreen` here, we will only have 1 screen

2024-08-22 07:15 UTC, WilhelmWesser approved these changes

2024-08-22 07:16 UTC, WilhelmWesser approved these changes

2024-08-22 07:47 UTC, fshabanov approved these changes

2024-08-22 07:47 UTC, merged